/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DataProtectionRouteImport } from './routes/data-protection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedUnderReviewRouteImport } from './routes/_authenticated/under-review'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSupportIdRouteImport } from './routes/_authenticated/support.$id'
import { Route as AuthenticatedProfileIdRouteImport } from './routes/_authenticated/profile.$id'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedCallIdRouteImport } from './routes/_authenticated/call.$id'
import { Route as AuthenticatedAdminVerifyRouteImport } from './routes/_authenticated/admin/verify'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminSuggestionsRouteImport } from './routes/_authenticated/admin/suggestions'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin/stories'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin/requests'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProtectionRoute = DataProtectionRouteImport.update({
  id: '/data-protection',
  path: '/data-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUnderReviewRoute =
  AuthenticatedUnderReviewRouteImport.update({
    id: '/under-review',
    path: '/under-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSupportIdRoute = AuthenticatedSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSupportRoute,
} as any)
const AuthenticatedProfileIdRoute = AuthenticatedProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProfileRoute,
} as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)
const AuthenticatedCallIdRoute = AuthenticatedCallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminVerifyRoute =
  AuthenticatedAdminVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuggestionsRoute =
  AuthenticatedAdminSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal': typeof AppealRoute
  '/contact': typeof ContactRoute
  '/data-protection': typeof DataProtectionRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRouteWithChildren
  '/under-review': typeof AuthenticatedUnderReviewRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/suggestions': typeof AuthenticatedAdminSuggestionsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verify': typeof AuthenticatedAdminVerifyRoute
  '/call/$id': typeof AuthenticatedCallIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal': typeof AppealRoute
  '/contact': typeof ContactRoute
  '/data-protection': typeof DataProtectionRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRouteWithChildren
  '/under-review': typeof AuthenticatedUnderReviewRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/suggestions': typeof AuthenticatedAdminSuggestionsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verify': typeof AuthenticatedAdminVerifyRoute
  '/call/$id': typeof AuthenticatedCallIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/appeal': typeof AppealRoute
  '/contact': typeof ContactRoute
  '/data-protection': typeof DataProtectionRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRouteWithChildren
  '/_authenticated/under-review': typeof AuthenticatedUnderReviewRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/_authenticated/admin/suggestions': typeof AuthenticatedAdminSuggestionsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verify': typeof AuthenticatedAdminVerifyRoute
  '/_authenticated/call/$id': typeof AuthenticatedCallIdRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
  '/_authenticated/support/$id': typeof AuthenticatedSupportIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appeal'
    | '/contact'
    | '/data-protection'
    | '/faq'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/stories'
    | '/suggestions'
    | '/terms'
    | '/testimonials'
    | '/vision'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/membership'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/support'
    | '/under-review'
    | '/verification'
    | '/admin/admins'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/suggestions'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/verify'
    | '/call/$id'
    | '/messages/$id'
    | '/profile/$id'
    | '/support/$id'
    | '/admin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appeal'
    | '/contact'
    | '/data-protection'
    | '/faq'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/stories'
    | '/suggestions'
    | '/terms'
    | '/testimonials'
    | '/vision'
    | '/dashboard'
    | '/matches'
    | '/membership'
    | '/messages'
    | '/onboarding'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/support'
    | '/under-review'
    | '/verification'
    | '/admin/admins'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/suggestions'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/verify'
    | '/call/$id'
    | '/messages/$id'
    | '/profile/$id'
    | '/support/$id'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/appeal'
    | '/contact'
    | '/data-protection'
    | '/faq'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/stories'
    | '/suggestions'
    | '/terms'
    | '/testimonials'
    | '/vision'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/matches'
    | '/_authenticated/membership'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/recommendations'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/under-review'
    | '/_authenticated/verification'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/suggestions'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verify'
    | '/_authenticated/call/$id'
    | '/_authenticated/messages/$id'
    | '/_authenticated/profile/$id'
    | '/_authenticated/support/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppealRoute: typeof AppealRoute
  ContactRoute: typeof ContactRoute
  DataProtectionRoute: typeof DataProtectionRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
  SuggestionsRoute: typeof SuggestionsRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-protection': {
      id: '/data-protection'
      path: '/data-protection'
      fullPath: '/data-protection'
      preLoaderRoute: typeof DataProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/under-review': {
      id: '/_authenticated/under-review'
      path: '/under-review'
      fullPath: '/under-review'
      preLoaderRoute: typeof AuthenticatedUnderReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/support/$id': {
      id: '/_authenticated/support/$id'
      path: '/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof AuthenticatedSupportIdRouteImport
      parentRoute: typeof AuthenticatedSupportRoute
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/call/$id': {
      id: '/_authenticated/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof AuthenticatedCallIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/verify': {
      id: '/_authenticated/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AuthenticatedAdminVerifyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suggestions': {
      id: '/_authenticated/admin/suggestions'
      path: '/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AuthenticatedAdminSuggestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRoute
  AuthenticatedAdminSuggestionsRoute: typeof AuthenticatedAdminSuggestionsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerifyRoute: typeof AuthenticatedAdminVerifyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRoute,
  AuthenticatedAdminSuggestionsRoute: AuthenticatedAdminSuggestionsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVerifyRoute: AuthenticatedAdminVerifyRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedSupportRouteChildren {
  AuthenticatedSupportIdRoute: typeof AuthenticatedSupportIdRoute
}

const AuthenticatedSupportRouteChildren: AuthenticatedSupportRouteChildren = {
  AuthenticatedSupportIdRoute: AuthenticatedSupportIdRoute,
}

const AuthenticatedSupportRouteWithChildren =
  AuthenticatedSupportRoute._addFileChildren(AuthenticatedSupportRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRouteWithChildren
  AuthenticatedUnderReviewRoute: typeof AuthenticatedUnderReviewRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedCallIdRoute: typeof AuthenticatedCallIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRouteWithChildren,
  AuthenticatedUnderReviewRoute: AuthenticatedUnderReviewRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedCallIdRoute: AuthenticatedCallIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AppealRoute: AppealRoute,
  ContactRoute: ContactRoute,
  DataProtectionRoute: DataProtectionRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
  SuggestionsRoute: SuggestionsRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
